spring:
  datasource:
    url: jdbc:h2:mem:music
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: false
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
