-- TABELA ARTISTA
CREATE TABLE IF NOT EXISTS ARTISTA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    nationality VARCHAR(255) NOT NULL,
    website VARCHAR(255) NOT NULL,
    profileImage BLOB NOT NULL
);

-- TABELA MUSICA
CREATE TABLE IF NOT EXISTS MUSICA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    durationSeconds INT NOT NULL,
    albumId INT NOT NULL,
    trackNumber INT NOT NULL
);

-- TABELA ALBUM
CREATE TABLE IF NOT EXISTS MUSICA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    year INT NOT NULL,
    imageCover BLOB NOT NULL,
    artistaId INT NOT NULL
);
